// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/lucasew/gaderno/internal/ui/layout"

type AgentData struct {
	TokenJSON string // json.Marshal of the shared token (may be "")
}

func Agent(d AgentData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<body class=\"min-h-full bg-base-100 text-base-content text-sm\"><header class=\"g-topbar sticky top-0 z-50 bg-base-100/90 backdrop-blur-sm border-b border-base-300\"><div class=\"g-topbar-inner\"><a href=\"/\" class=\"g-logo\" title=\"gaderno\" aria-label=\"gaderno home\"><img src=\"/static/logo.png\" width=\"32\" height=\"32\" alt=\"\"></a> <span class=\"g-topbar-title\">Agent</span> <span class=\"flex-1\"></span></div></header><main class=\"g-workspace max-w-xl\"><header class=\"mb-6\"><h1 class=\"text-2xl font-semibold tracking-tight text-balance\">Agent access</h1><p class=\"text-sm text-base-content/60 mt-1 max-w-prose\">Paste this into your coding agent. It will fetch <span class=\"font-code\">/SKILL.md</span> with the same token and work on this instance.</p></header><textarea id=\"agent-invite\" class=\"textarea textarea-bordered font-code w-full min-h-40\" readonly aria-label=\"Instruction for the agent\"></textarea><div class=\"mt-3 flex items-center gap-2\"><button type=\"button\" class=\"btn btn-primary\" id=\"agent-copy\">Copy</button> <span class=\"text-sm text-base-content/55\" id=\"agent-copy-status\" aria-live=\"polite\"></span></div></main>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = agentBoot(d.TokenJSON).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<script>\n\t\t\t\t(function () {\n\t\t\t\t\tvar boot = window.__GADERNO_AGENT__ || {};\n\t\t\t\t\tvar token = boot.token || \"\";\n\t\t\t\t\tvar origin = location.origin;\n\t\t\t\t\tvar lines = [\n\t\t\t\t\t\t\"Work on this gaderno instance.\",\n\t\t\t\t\t\t\"\",\n\t\t\t\t\t\t\"GET \" + origin + \"/SKILL.md\"\n\t\t\t\t\t];\n\t\t\t\t\tif (token) {\n\t\t\t\t\t\tlines.push(\"Authorization: Bearer \" + token);\n\t\t\t\t\t}\n\t\t\t\t\tlines.push(\"\");\n\t\t\t\t\tif (token) {\n\t\t\t\t\t\tlines.push(\"Follow that skill. Use the same origin and Bearer token on every request. Never put the token in a URL. Never log it.\");\n\t\t\t\t\t} else {\n\t\t\t\t\t\tlines.push(\"Follow that skill. Use the same origin on every request. No access token is configured.\");\n\t\t\t\t\t}\n\t\t\t\t\tvar text = lines.join(\"\\n\");\n\t\t\t\t\tvar area = document.getElementById(\"agent-invite\");\n\t\t\t\t\tif (area) area.value = text;\n\t\t\t\t\tvar btn = document.getElementById(\"agent-copy\");\n\t\t\t\t\tvar status = document.getElementById(\"agent-copy-status\");\n\t\t\t\t\tif (!btn) return;\n\t\t\t\t\tbtn.addEventListener(\"click\", function () {\n\t\t\t\t\t\tfunction ok() {\n\t\t\t\t\t\t\tif (status) status.textContent = \"Copied\";\n\t\t\t\t\t\t}\n\t\t\t\t\t\tfunction fail() {\n\t\t\t\t\t\t\tif (area) area.select();\n\t\t\t\t\t\t\tif (status) status.textContent = \"Select and copy\";\n\t\t\t\t\t\t}\n\t\t\t\t\t\tif (navigator.clipboard && navigator.clipboard.writeText) {\n\t\t\t\t\t\t\tnavigator.clipboard.writeText(text).then(ok).catch(fail);\n\t\t\t\t\t\t} else {\n\t\t\t\t\t\t\tfail();\n\t\t\t\t\t\t}\n\t\t\t\t\t});\n\t\t\t\t})();\n\t\t\t</script></body>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout.Document("Agent — gaderno").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
