// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/lucasew/gaderno/internal/ui/layout"

type WorkspaceData struct {
	Notebooks []string
}

func Workspace(d WorkspaceData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<body class=\"min-h-full bg-base-100 text-base-content text-sm\"><header class=\"g-topbar sticky top-0 z-50 bg-base-100/90 backdrop-blur-sm border-b border-base-300\"><div class=\"g-topbar-inner\"><a href=\"/\" class=\"g-logo\" title=\"gaderno\" aria-label=\"gaderno home\">G</a> <span class=\"g-topbar-title\">Workspace</span> <span class=\"flex-1\"></span> <details class=\"dropdown dropdown-end\"><summary class=\"g-icon-btn\" aria-label=\"Menu\" title=\"Menu\"><span class=\"g-avatar\" id=\"ws-avatar\" aria-hidden=\"true\">·</span></summary><ul class=\"menu dropdown-content bg-base-100 rounded-box z-50 w-52 p-2 shadow-md border border-base-300 text-sm mt-1\"><li class=\"menu-title text-xs\">Theme</li><li><button type=\"button\" class=\"theme-set\" data-theme=\"gaderno-light\">Light</button></li><li><button type=\"button\" class=\"theme-set\" data-theme=\"gaderno-dark\">Dark</button></li><li class=\"menu-title text-xs\">About</li><li><span class=\"text-xs text-base-content/60 pointer-events-none\">Local notebooks · server owns state</span></li></ul></details></div></header><main class=\"g-workspace\"><header class=\"mb-6\"><h1 class=\"text-2xl font-semibold tracking-tight text-balance\">Notebooks</h1><p class=\"text-sm text-base-content/60 mt-1 max-w-prose\">Open a notebook or create one. Kernels run on this host; the server holds the live document.</p></header>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if len(d.Notebooks) > 0 {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<ul class=\"g-nb-list\" role=\"list\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				for _, name := range d.Notebooks {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<li><a class=\"g-nb-row\" href=\"")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var3 templ.SafeURL
					templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinURLErrs(notebookOpenURL(name))
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/ui/pages/workspace.templ`, Line: 42, Col: 56}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\"><span class=\"g-nb-icon\" aria-hidden=\"true\"><svg width=\"18\" height=\"18\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M4 19.5A2.5 2.5 0 0 1 6.5 17H20\"></path> <path d=\"M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z\"></path> <path d=\"M8 7h8M8 11h6\"></path></svg></span> <span class=\"g-nb-name font-code\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var4 string
					templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(name)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/ui/pages/workspace.templ`, Line: 50, Col: 49}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</span> <span class=\"g-nb-chevron text-base-content/35\" aria-hidden=\"true\">→</span></a></li>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</ul>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<div class=\"g-empty\"><p class=\"font-medium\">No notebooks yet</p><p class=\"text-sm text-base-content/55 mt-1\">Create one below — a blank code cell is waiting.</p></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<form class=\"g-create mt-6\" method=\"post\" action=\"/api/notebooks\"><label class=\"sr-only\" for=\"nb-name\">Notebook file name</label> <input id=\"nb-name\" type=\"text\" name=\"name\" placeholder=\"name.ipynb\" required autocomplete=\"off\" class=\"input input-bordered font-code flex-1 min-w-0\"> <button class=\"btn btn-primary gap-1.5 shrink-0\" type=\"submit\"><svg width=\"16\" height=\"16\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" aria-hidden=\"true\"><path d=\"M12 5v14M5 12h14\"></path></svg> Create</button></form></main><script>\n\t\t\t\t(function () {\n\t\t\t\t\ttry {\n\t\t\t\t\t\tvar n = localStorage.getItem(\"gaderno-display-name\") || \"\";\n\t\t\t\t\t\tvar el = document.getElementById(\"ws-avatar\");\n\t\t\t\t\t\tif (el) el.textContent = (n.trim()[0] || \"?\").toUpperCase();\n\t\t\t\t\t} catch (e) {}\n\t\t\t\t})();\n\t\t\t</script></body>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout.Document("gaderno").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
